version: '2'

networks:
  front:
    driver: bridge

services:
  steamcmd:
    image: fernandoalves/steamcmd:latest 

  csgo:
    image: fernandoalves/csgo:latest
    volumes:
      - ./mounted/csgo:/var/lib/csgo
    ports:
      - "27015:27015/tcp"
      - "27016:27016/tcp"
      - "27015:27015/udp"
      - "27016:27016/udp"
      - "3478:3478/udp"
      - "4379:4379/udp"
      - "4380:4380/udp"
      - "51840:51840/udp"
    restart: always
    networks:
      - front
    environment:
      - GAME_TYPE=0         # 0 is Classic type. 1 is Gungame type.
      - GAME_MODE=1         # If game_type is 0 then mode 0 is Classic Casual and 1 is Classic Competitive. If game_type is 1 then mode 0 is Arms Race and 1 is Demolition.
      - MAP_GROUP=mg_bomb
      - MAP=de_dust2
      - RCON_PASSWORD=supersecret
      - UPDATE=true
