FROM steamcmd:latest
MAINTAINER fernandoasfj@gmail.com

RUN $STEAMCMD_HOME/steamcmd.sh +login anonymous +force_install_dir $HOME/csgo +app_update 740 validate +quit

EXPOSE 27015

WORKDIR $HOME/csgo
ENTRYPOINT $HOME/csgo/srcds_run
